import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, SafeAreaView, StyleSheet, Text, TextInput, useColorScheme, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { compareDevices, Device, searchDevices } from './src/api';
import { getFavorites, setFavorite } from './src/storage';

const money = (value: number | null | undefined) => value == null ? 'Нет данных' : `${Math.round(value).toLocaleString('ru-RU')} ₽`;
type Screen = 'search' | 'favorites' | 'compare';

export default function App() {
  const dark = useColorScheme() === 'dark';
  const colors = dark ? darkColors : lightColors;
  const [screen, setScreen] = useState<Screen>('search');
  const [query, setQuery] = useState(''); const [devices, setDevices] = useState<Device[]>([]);
  const [selected, setSelected] = useState<Device | null>(null); const [compare, setCompare] = useState<Device[]>([]);
  const [favorites, setFavorites] = useState<string[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { getFavorites().then(setFavorites); }, []);
  const visible = useMemo(() => screen === 'favorites' ? devices.filter((d) => favorites.includes(d.model_id)) : devices, [devices, favorites, screen]);
  async function search() { if (!query.trim()) return; setLoading(true); setError(''); try { setDevices(await searchDevices(query.trim())); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  async function toggleFavorite(id: string) { setFavorites(await setFavorite(id, !favorites.includes(id))); }
  async function loadCompare() { if (compare.length < 2) return; setLoading(true); try { setCompare((await compareDevices(compare.map((d) => d.model_id))).devices); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }
  return <SafeAreaView style={[styles.safe, { backgroundColor: colors.bg }]}><StatusBar style={dark ? 'light' : 'dark'} /><View style={styles.container}>
    <Text style={[styles.title, { color: colors.text }]}>Deprecio</Text>
    {selected ? <DeviceCard device={selected} favorite={favorites.includes(selected.model_id)} onFavorite={() => toggleFavorite(selected.model_id)} onBack={() => setSelected(null)} colors={colors} /> : <>
      {screen === 'search' && <View style={styles.search}><TextInput value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder="Модель устройства" placeholderTextColor={colors.muted} style={[styles.input, { color: colors.text, borderColor: colors.border }]} /><Pressable onPress={search} style={styles.button}><Text style={styles.buttonText}>Найти</Text></Pressable></View>}
      {screen === 'compare' ? <Compare devices={compare} onRemove={(id: string) => setCompare(compare.filter((d) => d.model_id !== id))} colors={colors} /> : <FlatList data={visible} keyExtractor={(d) => d.model_id} ListEmptyComponent={<Text style={{ color: colors.muted }}>{error || (screen === 'search' ? 'Введите модель для поиска' : 'Избранных устройств пока нет')}</Text>} refreshing={loading} onRefresh={search} renderItem={({ item }) => <Result device={item} favorite={favorites.includes(item.model_id)} compared={compare.some((d) => d.model_id === item.model_id)} onOpen={() => setSelected(item)} onFavorite={() => toggleFavorite(item.model_id)} onCompare={() => setCompare(compare.some((d) => d.model_id === item.model_id) ? compare.filter((d) => d.model_id !== item.model_id) : [...compare, item].slice(-3))} colors={colors} />} />}
      {error ? <Text style={styles.error}>{error}</Text> : null}<View style={[styles.tabs, { borderTopColor: colors.border }]}>{(['search', 'favorites', 'compare'] as Screen[]).map((tab) => <Pressable key={tab} onPress={() => setScreen(tab)} style={styles.tab}><Text style={{ color: screen === tab ? colors.accent : colors.muted }}>{tab === 'search' ? 'Поиск' : tab === 'favorites' ? `Избранное (${favorites.length})` : `Сравнение (${compare.length})`}</Text></Pressable>)}</View>
    </>}</View></SafeAreaView>;
}
function Result({ device, favorite, compared, onOpen, onFavorite, onCompare, colors }: any) { return <Pressable onPress={onOpen} style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.row}><View><Text style={[styles.name, { color: colors.text }]}>{device.name}</Text><Text style={{ color: colors.muted }}>{device.brand} · {device.tier}</Text></View><Pressable onPress={onFavorite}><Text style={styles.star}>{favorite ? '★' : '☆'}</Text></Pressable></View><Pressable onPress={onCompare}><Text style={{ color: colors.accent }}>{compared ? 'Убрать из сравнения' : 'Добавить к сравнению'}</Text></Pressable></Pressable>; }
function DeviceCard({ device, favorite, onFavorite, onBack, colors }: any) { return <View><Pressable onPress={onBack}><Text style={{ color: colors.accent }}>← Назад</Text></Pressable><Text style={[styles.heading, { color: colors.text }]}>{device.name}</Text><Pressable onPress={onFavorite}><Text style={styles.star}>{favorite ? '★ Избранное' : '☆ В избранное'}</Text></Pressable>{[['MSRP', money(device.msrp_rub)], ['RV', device.residual_value_percent == null ? 'Нет данных' : `${device.residual_value_percent.toFixed(1)}%`], ['Объявления', device.market_stats?.listings_count ?? 0], ['Прогноз', device.forecast_summary || 'Нет данных']].map(([label, value]) => <View key={label} style={[styles.metric, { borderBottomColor: colors.border }]}><Text style={{ color: colors.muted }}>{label}</Text><Text style={{ color: colors.text }}>{value}</Text></View>)}</View>; }
function Compare({ devices, onRemove, colors }: any) { return <View><Text style={[styles.heading, { color: colors.text }]}>Сравнение</Text>{devices.length < 2 ? <Text style={{ color: colors.muted }}>Выберите 2–3 устройства в поиске</Text> : <View style={styles.table}>{['MSRP', 'RV', 'Объявления', 'Прогноз'].map((label) => <View key={label} style={styles.metric}><Text style={{ color: colors.muted }}>{label}</Text>{devices.map((d: Device) => <Text key={d.model_id} style={{ color: colors.text, flex: 1 }}>{label === 'MSRP' ? money(d.msrp_rub) : label === 'RV' ? `${d.residual_value_percent?.toFixed(1) ?? '—'}%` : label === 'Объявления' ? d.market_stats?.listings_count ?? 0 : d.forecast_summary || '—'}</Text>)}</View>)}</View>}{devices.map((d: Device) => <Pressable key={d.model_id} onPress={() => onRemove(d.model_id)}><Text style={{ color: colors.accent }}>Убрать {d.name}</Text></Pressable>)}</View>; }
const lightColors = { bg: '#f7f8fa', card: '#fff', text: '#17202a', muted: '#68737d', border: '#dce1e6', accent: '#1769aa' }; const darkColors = { bg: '#111417', card: '#1d2227', text: '#f1f3f5', muted: '#aab3bb', border: '#3a4249', accent: '#72b7f2' };
const styles = StyleSheet.create({ safe: { flex: 1 }, container: { flex: 1, padding: 20 }, title: { fontSize: 28, fontWeight: '700', marginBottom: 18 }, search: { flexDirection: 'row', gap: 8, marginBottom: 16 }, input: { flex: 1, borderWidth: 1, borderRadius: 6, padding: 12 }, button: { backgroundColor: '#1769aa', borderRadius: 6, justifyContent: 'center', paddingHorizontal: 16 }, buttonText: { color: '#fff', fontWeight: '600' }, card: { borderWidth: 1, borderRadius: 6, padding: 14, marginBottom: 10, gap: 12 }, row: { flexDirection: 'row', justifyContent: 'space-between' }, name: { fontSize: 17, fontWeight: '600' }, star: { color: '#d18a00', fontSize: 18 }, heading: { fontSize: 23, fontWeight: '700', marginVertical: 18 }, metric: { flexDirection: 'row', gap: 12, paddingVertical: 12, borderBottomWidth: 1 }, table: { marginBottom: 12 }, tabs: { flexDirection: 'row', borderTopWidth: 1, paddingTop: 14, marginTop: 12 }, tab: { flex: 1, alignItems: 'center' }, error: { color: '#c0392b', marginVertical: 8 } });